// words.js
const allWords = [
  { en: "as you know", ja: "ご存知のように" },
  { en: "labor", ja: "労働" },
  { en: "thanksgiving", ja: "感謝" },
  { en: "Labor Thanksgiving Day", ja: "勤労感謝の日" },
  { en: "discussion", ja: "討議、討論" },
  { en: "relate", ja: "~と関係がある" },
  { en: "be related to", ja: "~と関係がある" },
  { en: "a few", ja: "多少の~" },
  { en: "opinion", ja: "意見" },
  { en: "in my opinion", ja: "私の考えでは" },
  { en: "agree with", ja: "~に賛成する" },
  { en: "hobby", ja: "趣味" },
  { en: "both and", ja: "~も･･･も両方とも" },
  { en: "get home", ja: "帰宅する" },

  // --- 3枚目 ---
  { en: "the other day", ja: "先日" },
  { en: "Sweden", ja: "スウェーデン" },
  { en: "marry", ja: "~と結婚する" },
  { en: "get married", ja: "結婚する" },
  { en: "common", ja: "一般的な、ありふれた、普通の" },
  { en: "Swedish", ja: "スウェーデンの" },
  { en: "housework", ja: "家事" },
  { en: "child-raising", ja: "子育て" },
  { en: "grow up", ja: "大人になる" },
  { en: "cooperate", ja: "協力する" },
  { en: "wife", ja: "妻" },
  { en: "university", ja: "大学" },
  { en: "researcher", ja: "研究者" },
  { en: "for sure", ja: "確実に、確実な" },
  { en: "certainly", ja: "確かに" },
  { en: "overtime", ja: "時間外に" },
  { en: "private", ja: "私的な" },
  { en: "we've", ja: "we have の短縮形" },
  { en: "confirm", ja: "確認する、確かめる" },
  { en: "argument", ja: "論点" },
  { en: "neither", ja: "~もまた･･･ない" },
  { en: "Me, neither.", ja: "私もまたそうではありません。" },
  { en: "work-life", ja: "仕事と生活の" },
 
  // --- 5枚目 ---
  { en: "prayer", ja: "祈り" },
  { en: "teenager", ja: "ティーンエージャー" },
  { en: "tram", ja: "路面電車" },
  { en: "in service", ja: "正常に動いて" },
  { en: "nearly", ja: "ほぼ" },
  { en: "Hiroshima Castle", ja: "広島城" },
  { en: "memorial", ja: "記念の" },
  { en: "Peace Memorial Park", ja: "平和記念公園" },
  { en: "in themselves", ja: "それら自体で" },
  { en: "reconstruction", ja: "復興" },
  { en: "atomic", ja: "原子の、原子力の" },
  { en: "atomic bomb", ja: "原子爆弾" },
  { en: "drop", ja: "~を落とす" },
  { en: "destroy", ja: "破壊する" },
  { en: "instant", ja: "瞬間" },
  { en: "in an instant", ja: "一瞬にして" },
  { en: "amazingly", ja: "驚くべきことに" },
  { en: "conductor", ja: "車掌" },
  { en: "schoolgirl", ja: "女学生" },
  { en: "worker", ja: "労働者" },
  { en: "A Story of a Girl Who Survived the Atomic Bomb", ja: "『原爆を生き抜いた少女の話』" },
  { en: "strength", ja: "強さ" },
  { en: "recover", ja: "立ち直る" },
  { en: "severe", ja: "深刻な" },
  { en: "hear of", ja: "~のことを耳にする" },
  { en: "film", ja: "映画" },
  { en: "animated film", ja: "アニメーション映画" },

  // --- 6枚目 ---
  { en: "be shocked at", ja: "~にショックを受ける" },
  { en: "scene", ja: "場面" },
  { en: "lose", ja: "失う" },
  { en: "terrible", ja: "ひどい" },
  { en: "accident", ja: "事故" },
  { en: "reality", ja: "現実" },
  { en: "carry on with", ja: "~をがんばり通す" },
  { en: "bring up", ja: "~を育てる (raise/bring up)" },
  { en: "sitting", ja: "現職の" },
  { en: "president", ja: "大統領" },
  { en: "make a speech", ja: "スピーチをする" },
  { en: "cloudless", ja: "晴れ渡った" },
  { en: "death", ja: "死、破滅" },
  { en: "realize", ja: "~を実感する" },
  { en: "importance", ja: "重大さ" },
  { en: "Hiroshima Peace Memorial Museum", ja: "広島平和記念資料館" },
  { en: "entrust", ja: "委ねる" },
  { en: "repeat", ja: "繰り返す" },
  { en: "itself", ja: "それ自体" },
  { en: "instead", ja: "そのかわりとして" },
  { en: "pray", ja: "祈る" },

  // --- 7枚目 ---
  { en: "down", ja: "元気のない" },
  { en: "argument", ja: "口論、議論" },
  { en: "high school", ja: "高校" },
  { en: "choose", ja: "選ぶ" },
  { en: "envious", ja: "うらやましい" },
  { en: "mmm", ja: "うーん" },
  { en: "up to", ja: "~次第である" },
  { en: "think over", ja: "~をよく考える" },
  { en: "speech", ja: "スピーチ、演説" },
  { en: "priority", ja: "優先事項" },
  { en: "wish", ja: "~を強く望む" },
  { en: "the same as", ja: "･･･と同じ" },
  { en: "unique", ja: "特有の" },
  { en: "on one's own", ja: "自分で" },
  { en: "ourselves", ja: "私たち自身" },
  { en: "Italian", ja: "イタリア語" },
  { en: "wouldn't", ja: "would not の短縮形" },
  { en: "German", ja: "ドイツ語" },
  { en: "rich", ja: "金持ちの、豊かな" },
  { en: "million", ja: "100万" },
  { en: "yen", ja: "〔通貨の〕円" },
  { en: "village", ja: "村" },
  { en: "right now", ja: "今すぐ" },
  { en: "have trouble", ja: "苦労する、困難である" },
  { en: "cellphone", ja: "携帯電話" },
  { en: "border", ja: "境界、国境" },
  { en: "ceremony", ja: "式典" },
  { en: "easy to", ja: "~しやすい" },
  { en: "aquarium", ja: "水族館" },

  // --- 8枚目 ---
  { en: "truth", ja: "真実" },
  { en: "discuss", ja: "話し合う" },
  { en: "lift", ja: "~を持ち上げる" },
  { en: "smartphone", ja: "スマートフォン" },
  { en: "go for a drive", ja: "ドライブする、ドライブに行く" },
  { en: "cook", ja: "料理人" },
  { en: "silly", ja: "愚かな、ばかな" },
  { en: "jog", ja: "ジョギングする" },
  { en: "hair style", ja: "髪型" },
  { en: "astronaut", ja: "宇宙飛行士" },
  { en: "apologize to", ja: "~に謝る" },
  { en: "some time", ja: "いつか、そのうち" },
  { en: "come over to", ja: "~にやって来る" },
  { en: "a car navigation system", ja: "カーナビ" },
  { en: "bakery", ja: "パン屋" },
  { en: "the World Cup final", ja: "ワールドカップ決勝戦" },
  { en: "participate in", ja: "~に参加する" },
  { en: "take a break", ja: "休みをとる" },
  { en: "brake", ja: "ブレーキ" },
  { en: "modern", ja: "現代の" },
  { en: "chain", ja: "チェーン、鎖" },
  { en: "cupboard", ja: "戸棚、食器棚" },
  { en: "classical music", ja: "クラシック" },
  { en: "be sure of", ja: "~を確信している" },
  { en: "be worried about", ja: "~を心配している" },
  { en: "refuse to", ja: "~するのを拒む" },
  { en: "be aware of", ja: "~に気づいている" },
  { en: "dislike", ja: "~が嫌いである" },
  { en: "imagine", ja: "~を想像する" },
  { en: "rude", ja: "無礼な" },
  { en: "be ashamed of", ja: "~を恥ずかしく思う" },
  { en: "inconvenient", ja: "不便な" },
  { en: "clap", ja: "〈手など〉をたたく" },
  { en: "environment", ja: "環境" }
];