// words.js (テスト本番仕様：頭文字・語数指定つき)
const allWords = [
  { en: "Italian", ja: "イタリア語" },
  { en: "importance", ja: "重大さ <i>" },
  { en: "astronaut", ja: "宇宙飛行士" },
  { en: "truth", ja: "真実 <t>" },
  { en: "reality", ja: "現実" },
  { en: "imagine", ja: "~を想像する" },
  { en: "cellphone", ja: "携帯電話" },
  { en: "teenager", ja: "ティーンエイジャー" },
  { en: "cooperate", ja: "協力する" },
  { en: "argument", ja: "口論、議論 <a>" },
  { en: "recover", ja: "立ち直る <r>" },
  { en: "wife", ja: "妻" },
  { en: "cook", ja: "料理人" },
  { en: "certainly", ja: "確かに <c>" },
  { en: "realize", ja: "~を実感する <r>" },
  { en: "priority", ja: "優先事項" },
  { en: "village", ja: "村" },
  { en: "dislike", ja: "~が嫌いである" },
  { en: "ourselves", ja: "私たち自身" },
  { en: "researcher", ja: "研究者" },
  { en: "clap", ja: "〈手など〉をたたく" },
  { en: "environment", ja: "環境" },
  { en: "reconstruction", ja: "復興" },
  { en: "hobbies", ja: "趣味 【複数形】" },
  { en: "aquarium", ja: "水族館" },
  { en: "confirm", ja: "確認する、確かめる <c>" },
  { en: "conductor", ja: "車掌" },
  { en: "Swedish", ja: "スウェーデンの" },
  { en: "common", ja: "一般的な、ありふれた、普通の <c>" },
  { en: "opinion", ja: "意見" },
  { en: "president", ja: "大統領" },
  { en: "yen", ja: "〔通貨の〕円" },
  { en: "severe", ja: "深刻な <s>" },
  { en: "entrust", ja: "委ねる <e>" },
  { en: "chain", ja: "チェーン、鎖" },
  { en: "lift", ja: "~を持ち上げる" },
  { en: "prayer", ja: "祈り" },
  { en: "discussion", ja: "討議、討論 <d>" },
  { en: "drop", ja: "~を落とす <d>" },
  { en: "envious", ja: "うらやましい <e>" },
  { en: "housework", ja: "家事" },
  { en: "wish", ja: "~を強く望む <w>" },
  { en: "university", ja: "大学 <u>" },
  { en: "instead", ja: "その代わりとして" },
  { en: "private", ja: "私的な" },
  { en: "silly", ja: "愚かな、ばかな <s>" },
  { en: "strength", ja: "強さ" },
  { en: "rude", ja: "無礼な" },
  { en: "accident", ja: "事故" },
  { en: "million", ja: "100万" },
  { en: "cloudless", ja: "晴れ渡った" },
  { en: "German", ja: "ドイツ語" },
  { en: "memorial", ja: "記念の" },
  { en: "inconvenient", ja: "不便な" },
  { en: "death", ja: "死、破滅" },
  { en: "modern", ja: "現代の <m>" },
  { en: "border", ja: "境界、国境" },
  { en: "overtime", ja: "時間外に <o>" },
  { en: "amazingly", ja: "驚くべきことに" },
  { en: "unique", ja: "特有の <u>" },
  { en: "destroy", ja: "破壊する <d>" },
  { en: "sitting", ja: "現職の" },
  { en: "ceremony", ja: "式典" },
  { en: "bakery", ja: "パン屋" },
  { en: "terrible", ja: "ひどい <t>" },
  { en: "nearly", ja: "ほぼ <n>" },
  { en: "a few", ja: "多少の 【2語】" },
  { en: "grow up", ja: "大人になる 【2語】" },
  { en: "right now", ja: "今すぐ 【2語】" },
  { en: "in service", ja: "正常に動いて 【2語】" },
  { en: "get married", ja: "結婚する 【2語】" },
  { en: "classical music", ja: "クラシック音楽 【2語】" },
  { en: "up to", ja: "~次第である 【2語】" },
  { en: "participate in", ja: "~に参加する 【2語】" },
  { en: "bring up", ja: "~を育てる 【2語】" },
  { en: "agree with", ja: "~に賛成する 【2語】" },
  { en: "animated film", ja: "アニメーション映画 【2語】" },
  { en: "both and", ja: "~も･･･も両方とも 【2語】" },
  { en: "Me, neither.", ja: "私もまたそうではありません。 【2語】" },
  { en: "have trouble", ja: "苦労する、困難である 【2語】" },
  { en: "apologize to", ja: "~に謝る 【2語】" },
  { en: "on one's own", ja: "自分で 【3語】" },
  { en: "think over", ja: "~をよく考える 【2語】" },
  { en: "the other day", ja: "先日 【3語】" },
  { en: "in my opinion", ja: "私の考えでは 【3語】" },
  { en: "as you know", ja: "ご存じのように 【3語】" },
  { en: "be related to", ja: "~と関係がある 【3語】" },
  { en: "be ashamed of", ja: "~を恥ずかしく思う 【3語】" },
  { en: "be aware of", ja: "~に気づいている 【3語】" },
  { en: "be worried about", ja: "~を心配している 【3語】" },
  { en: "in an instant", ja: "一瞬にして 【3語】" },
  { en: "make a speech", ja: "スピーチをする 【3語】" },
  { en: "take a break", ja: "休みをとる 【3語】" },
  { en: "the same as", ja: "･･･と同じ(~) 【3語】" },
  { en: "carry on with", ja: "~をがんばり通す 【3語】" },
  { en: "be shocked at", ja: "~にショックを受ける 【3語】" },
  { en: "Labor Thanksgiving Day", ja: "勤労感謝の日 【3語】" },
  { en: "a car navigation system", ja: "カーナビ (カーナビゲーション装置) 【4語】" },
  { en: "go for a drive", ja: "ドライブする、ドライブに行く 【4語】" },
  { en: "A Story of a Girl Who Survived the Atomic Bomb", ja: "『原爆に遭った少女の話』(書名) 【10語】" }
];